---
# Download install files
- name: Download SAP install files
  script: scripts/Download-SAPFiles.ps1 >
    -StorageAccountName "{{ storage_account_name }}"
    -StorageAccountKey "{{ storage_account_key }}"
    -FileShareUri "{{ file_share_uri }}"
    -Folders "CRMJAVAInstallStack"

- name: Copy commmon Java XML file
  template:
    src: "templates/MP_Stack_CRM_JAVA_NEW_INSTALL.j2"
    dest: "C:\\Install\\CRMJAVAInstallStack\\MP_Stack_AJ{{ environment_instance_count }}_CRM_JAVA_NEW_INSTALL.xml"
    newline_sequence: '\r\n'

- include_tasks:
    name: java.yaml

- include_tasks:
    name: sum.yaml
  when: ansible_hostname == pas_host

