---
- win_reboot:
    reboot_timeout: 120

- name: sap_copy_sql4sap_files
  script: scripts/sap_copy_sql4sap_files.ps1 >
    -storName "{{ storage_account_name }}"
    -storKey "{{ storage_account_key }}"

- name: Run SAP installer for ASCS
  win_shell: C:\Packages\SAP\SQL4SAP\SQL4SAP.bat -Verb runAs -WindowStyle Hidden -ArgumentList " -i MSSQLSERVER -u BUILTIN\Administrators /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /SQLSYSADMINACCOUNTS=BUILTIN\Administrators /FEATURES=BC,BOL,Conn,SSMS,ADV_SSMS,SQLEngine,Fulltext,SDK,ADV_SSMS,SNAC_SDK /UpdateEnabled=TRUE /UpdateSource=C:\Packages\SAP\installFiles\51050563-RDBMS-MSSQLSRV-2014 SP1 CU1-SQL4SAP-only\51050563\x86-x64\Patches\X64"

- name: sleep for 900 seconds and continue with play
  wait_for: timeout=900
  delegate_to: localhost

- name: Stop service MSSQLSERVICE
  win_service:
    name: MSSQLSERVER
    state: Stopped
    force_dependent_services: yes

- name: Set root user password
  mysql_user: name=root
              host="{{ item }}"
              password="{{ mysql_root_password }}"
              check_implicit_admin=yes
              login_user="{{ mysql_user }}"
              login_password="{{ mysql_old_root_password }}"
              state=present

# Create directory structure for SAP database
- name: Create directory structure for SAP database
  win_file:
    path: "I:\\{{ environment_sid }}\\{{ environment_sid }}{{ item }}"
    state: directory
  with_items:
    - LOG
    - DATA1
    - DATA2
    - DATA3
    - DATA4
    - DATA5
    - DATA6
    - DATA7
    - DATA8
  when: ('"data-crm" in hostvars[inventory_hostname].group_names') or
        ('"data-isu" in hostvars[inventory_hostname].group_names')