
USE $(database)
GO

/****** Delete triggers of EDIDC ******/
IF EXISTS (SELECT * FROM sys.triggers WHERE name = '/1LT/00000506DEL')
	DROP TRIGGER $(schema).[/1LT/00000506DEL]
GO
IF EXISTS (SELECT * FROM sys.triggers WHERE name = '/1LT/00000506UPD1')
	DROP TRIGGER $(schema).[/1LT/00000506UPD1]
GO
IF EXISTS (SELECT * FROM sys.triggers WHERE name = '/1LT/00000506INS')
	DROP TRIGGER $(schema).[/1LT/00000506INS]
GO


/****** Delete triggers for EMMA_CASE ******/
IF EXISTS (SELECT * FROM sys.triggers WHERE name = '/1LT/00000941DEL')
	DROP TRIGGER $(schema).[/1LT/00000941DEL]
GO
IF EXISTS (SELECT * FROM sys.triggers WHERE name = '/1LT/00000941INS')
	DROP TRIGGER $(schema).[/1LT/00000941INS]
GO
IF EXISTS (SELECT * FROM sys.triggers WHERE name = '/1LT/00000941UPD1')
	DROP TRIGGER $(schema).[/1LT/00000941UPD1]
GO


/****** Delet indexes of EDIDC ******/
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDIDC~1')
	DROP INDEX [EDIDC~1] ON $(schema).[EDIDC]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDIDC~2')
	DROP INDEX [EDIDC~2] ON $(schema).[EDIDC]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDIDC~3')
	DROP INDEX [EDIDC~3] ON $(schema).[EDIDC]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EDIDC~4')
	DROP INDEX [EDIDC~4] ON $(schema).[EDIDC]
GO


/****** Delete indexes of SRRELROLES ******/
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'SRRELROLES~001')
	DROP INDEX [SRRELROLES~001] ON $(schema).[SRRELROLES]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'SRRELROLES~002')
	DROP INDEX [SRRELROLES~002] ON $(schema).[SRRELROLES]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'SRRELROLES~003')
	DROP INDEX [SRRELROLES~003] ON $(schema).[SRRELROLES]
GO

/****** Delete indexes for EMMA_CASE ******/
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~1')
	DROP INDEX [EMMA_CASE~1] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~2')
	DROP INDEX [EMMA_CASE~2] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~3')
	DROP INDEX [EMMA_CASE~3] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~4')
	DROP INDEX [EMMA_CASE~4] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~5')
	DROP INDEX [EMMA_CASE~5] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~Z01')
	DROP INDEX [EMMA_CASE~Z01] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~ZAP')
	DROP INDEX [EMMA_CASE~ZAP] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~ZBP')
	DROP INDEX [EMMA_CASE~ZBP] ON $(schema).[EMMA_CASE]
GO
IF EXISTS (SELECT * FROM sys.indexes WHERE name = 'EMMA_CASE~ZEX')
	DROP INDEX [EMMA_CASE~ZEX] ON $(schema).[EMMA_CASE]
GO
