USE $(database)
GO

/****** Create trigger on EMMA_CASE ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 CREATE TRIGGER $(schema).[/1LT/00000941UPD1]   ON $(schema).[EMMA_CASE]   FOR UPDATE   AS   BEGIN    set nocount on if exists (select * from inserted where CLIENT = '100' ) BEGIN     IF UPDATE([CLIENT]) OR     UPDATE([CASENR])     BEGIN   INSERT INTO [/1CADMC/00000941]   SELECT CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [CLIENT],          [CASENR],           'D'     FROM deleted   INSERT INTO [/1CADMC/00000941]   SELECT CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [CLIENT],          [CASENR],           'I'     FROM inserted     END   ELSE BEGIN   INSERT INTO [/1CADMC/00000941]   SELECT  CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [CLIENT],          [CASENR],           'U'     FROM inserted    END   END END ;
GO

/****** 2 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 CREATE TRIGGER $(schema).[/1LT/00000941INS] ON $(schema).[EMMA_CASE] FOR INSERT AS set nocount on if exists (select * from inserted where CLIENT = '100' ) BEGIN INSERT INTO [/1CADMC/00000941]   SELECT  CONVERT(VARCHAR, GETUTCDATE(), 121), 0,     [CLIENT],          [CASENR],          'I'     FROM inserted END ;
GO

/****** 3 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 CREATE TRIGGER $(schema).[/1LT/00000941DEL]   ON $(schema).[EMMA_CASE]   FOR DELETE   AS     set nocount on if exists (select * from deleted where CLIENT = '100' ) BEGIN INSERT INTO [/1CADMC/00000941]   SELECT  CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [CLIENT],          [CASENR],         'D'     FROM deleted END ;
GO





/****** Create index of EMMA_CASE ******/
CREATE NONCLUSTERED INDEX [EMMA_CASE~1] ON $(schema).[EMMA_CASE]
(
	[MAINOBJTYPE] ASC,
	[MAINOBJKEY] ASC,
	[CCAT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 2 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~2] ON $(schema).[EMMA_CASE]
(
	[STATUS] ASC,
	[RUNID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 3 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~3] ON $(schema).[EMMA_CASE]
(
	[CURRPROC] ASC,
	[STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 4 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~4] ON $(schema).[EMMA_CASE]
(
	[STATUS] ASC,
	[CCAT] ASC,
	[CTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 5 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~5] ON $(schema).[EMMA_CASE]
(
	[RUNID] ASC,
	[STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 6 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~Z01] ON $(schema).[EMMA_CASE]
(
	[MAINOBJKEY] ASC,
	[STATUS] ASC,
	[MAINOBJTYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 7 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~ZAP] ON $(schema).[EMMA_CASE]
(
	[APPLICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 8 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~ZBP] ON $(schema).[EMMA_CASE]
(
	[BPCODE] ASC,
	[MAINOBJTYPE] ASC,
	[CREATED_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

/****** 9 ******/

CREATE NONCLUSTERED INDEX [EMMA_CASE~ZEX] ON $(schema).[EMMA_CASE]
(
	[CLIENT] ASC,
	[EXT_UI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
