USE $(database)
GO


/****** Create trigger EDIDC******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 CREATE TRIGGER $(schema).[/1LT/00000506DEL]   ON $(schema).[EDIDC]   FOR DELETE   AS     set nocount on if exists (select * from deleted where MANDT = '100' ) BEGIN INSERT INTO [/1CADMC/00000506]   SELECT  CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [MANDT],          [DOCNUM],         'D'     FROM deleted END ;
GO
/****** 2 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 CREATE TRIGGER $(schema).[/1LT/00000506INS] ON $(schema).[EDIDC] FOR INSERT AS set nocount on if exists (select * from inserted where MANDT = '100' ) BEGIN INSERT INTO [/1CADMC/00000506]   SELECT  CONVERT(VARCHAR, GETUTCDATE(), 121), 0,     [MANDT],          [DOCNUM],          'I'     FROM inserted END ;
GO

/****** 3 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

 CREATE TRIGGER $(schema).[/1LT/00000506UPD1]   ON $(schema).[EDIDC]   FOR UPDATE   AS   BEGIN    set nocount on if exists (select * from inserted where MANDT = '100' ) BEGIN     IF UPDATE([MANDT]) OR     UPDATE([DOCNUM])     BEGIN   INSERT INTO [/1CADMC/00000506]   SELECT CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [MANDT],          [DOCNUM],           'D'     FROM deleted   INSERT INTO [/1CADMC/00000506]   SELECT CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [MANDT],          [DOCNUM],           'I'     FROM inserted     END   ELSE BEGIN   INSERT INTO [/1CADMC/00000506]   SELECT  CONVERT(VARCHAR, GETUTCDATE(), 121), 0,      [MANDT],          [DOCNUM],           'U'     FROM inserted    END   END END ;
GO


/****** Create index for EDIDC TAKES 20 mins ******/
CREATE NONCLUSTERED INDEX [EDIDC~4] ON $(schema).[EDIDC]
(
	[MANDT] ASC,
	[STATUS] ASC,
	[MESTYP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY];
GO

/******  TAKES 15 mins ******/
CREATE NONCLUSTERED INDEX [EDIDC~3] ON $(schema).[EDIDC]
(
	[MANDT] ASC,
	[MESTYP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY];
GO

/******3 ******/
CREATE NONCLUSTERED INDEX [EDIDC~2] ON $(schema).[EDIDC]
(
	[MANDT] ASC,
	[UPDDAT] ASC,
	[UPDTIM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY];
GO

/****** 4 ******/
CREATE NONCLUSTERED INDEX [EDIDC~1] ON $(schema).[EDIDC]
(
	[MANDT] ASC,
	[STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY];
GO


