ansible_connection: winrm
ansible_port: 5986
ansible_user: azureadmin
ansible_winrm_server_cert_validation: ignore
isu_sid: "I{{ datacentre }}{{ environment_instance_count }}"
wd_sid: "W{{ datacentre }}{{ environment_instance_count }}"
crm_sid: "C{{ datacentre }}{{ environment_instance_count }}"
crm_java: "AJ{{ environment_instance_count }}"