/**** RUN THEM IN PARALLEL SEPARATE WINDOWS *****/

DECLARE @BATCH INT=1 WHILE( @BATCH <= 22 ) BEGIN UPDATE TOP(20000000) $(schema).CRMD_ORDERADM_H SET    LOGICAL_SYSTEM = $(crm_target_ls) WHERE  LOGICAL_SYSTEM = $(crm_source_ls) SET @BATCH=@BATCH + 1 END -- (1 hour 45 mins)
DECLARE @BATCH INT=1 WHILE( @BATCH <= 20 ) BEGIN UPDATE TOP(2000000) $(schema).CRMM_BUT_LNK0020 SET    HOME_SYSTEM = $(crm_target_ls) WHERE  HOME_SYSTEM = $(crm_source_ls) SET @BATCH=@BATCH + 1 END -- (10 mins)
DECLARE @BATCH INT=1 WHILE( @BATCH <= 20 ) BEGIN UPDATE TOP(2000000) $(schema).CRMM_BUT_LNK0030 SET    HOME_SYSTEM = $(crm_target_ls) WHERE  HOME_SYSTEM = $(crm_source_ls) SET @BATCH=@BATCH + 1 END -- (6 mins)
DECLARE @BATCH INT=1 WHILE( @BATCH <= 11 ) BEGIN UPDATE TOP(2000000) $(schema).GEOOBJR SET    LOGSYS = $(crm_target_ls) WHERE  LOGSYS = $(crm_source_ls) SET @BATCH=@BATCH + 1 END -- (4 mins)
DECLARE @BATCH INT=1 WHILE( @BATCH <= 5 ) BEGIN UPDATE TOP(2000000) $(schema).COMM_PR_FRG_REL   SET  LOGSYS = $(isu_target_ls) WHERE  LOGSYS = $(isu_source_ls) SET @BATCH=@BATCH + 1 END -- (3 mins)
DECLARE @BATCH INT=1 WHILE( @BATCH <= 5 ) BEGIN UPDATE TOP(2000000) $(schema).COMM_PRPRDCATR   SET  LOGSYS = $(isu_target_ls) WHERE  LOGSYS = $(isu_source_ls) SET @BATCH=@BATCH + 1 END -- (1 min)
DECLARE @BATCH INT=1 WHILE( @BATCH <= 5 ) BEGIN UPDATE TOP(2000000) $(schema).COMM_PRODUCT   SET  LOGSYS = $(isu_target_ls) WHERE  LOGSYS = $(isu_source_ls) SET @BATCH=@BATCH + 1 END -- (2 mins)
DECLARE @BATCH INT=1 WHILE( @BATCH <= 3 ) BEGIN UPDATE TOP(2000000) $(schema).EDIDC  SET  RCVPRN = $(bw_target_ls) WHERE  RCVPRN = $(bw_source_ls) SET @BATCH=@BATCH + 1 END -- (5 mins)