---
- name: sap_sql_copy_blob_files
  script: scripts/sap_sql_copy_blob_files.ps1 >
    -storName "{{ aaaSapAutomationStorageName }}"
    -storKey "{{ aaaSapAutomationSaKey }}"

- name: SQL Script to change database logical file names in SQL
  win_shell: sqlcmd.exe -i "C:\Packages\SAP\sqlScripts\SQLPostConfig\sap_post_config_01.sql" -v database="{{ environment_sid }}"

- name: Stop service MSSQLSERVICE
  win_service:
    name: MSSQLSERVER
    state: Stopped
    force_dependent_services: yes

- name: sap_rename_db_file
  script: scripts/sap_rename_db_file.ps1 >
    -SID "{{ environment_sid }}"

- name: Start service MSSQLSERVICE
  win_service:
    name: MSSQLSERVER
    state: Started
    force_dependent_services: yes
    
- name:  SQL Script to move temp db files and create additional temp db files
  win_shell: sqlcmd.exe -i "C:\Packages\SAP\sqlScripts\SQLPostConfig\sap_post_config_02.sql" -v database="{{ environment_sid }}"
  
- name: Start service MSSQLSERVICE
  win_service:
    name: MSSQLSERVER
    state: restarted
    force_dependent_services: yes

- name: Start service MSSQLSERVICE
  win_service:
    name: MSSQLSERVER
    state: started
    force_dependent_services: yes

- name: Start service MSSQLSERVICE, if not started
  win_service:
    name: SQLSERVERAGENT
    state: started
    force_dependent_services: yes

- name: Remove TempDB files
  win_file:
    path: "C:\\Program Files\\Microsoft SQL Server\\MSSQL12.MSSQLSERVER\\MSSQL\\DATA\\{{ item }}"
    state: absent
  with_items:
    - tempdev.mdf
    - templog.ldf

- name: Grant privileges to install user
  win_user_right:
    name: "{{ item }}"
    users:
    - "NT Service\\MSSQLSERVER"
    action: add
  with_items:
    - SeLockMemoryPrivilege
    - SeManageVolumePrivilege

- name: Update registry with Trace Flags
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Microsoft SQL Server\\MSSQL12.MSSQLSERVER\\MSSQLServer\\Parameters"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: string
  with_items:
    - { name: SQLArg3, data: -T617 }
    - { name: SQLArg4, data: -T1117 }
    - { name: SQLArg5, data: -T1118 }
    - { name: SQLArg6, data: -T2371 }
    - { name: SQLArg7, data: -T3051 }
    - { name: SQLArg8, data: -T8075 }
    - { name: SQLArg9, data: -T8080 }

- name: Start service MSSQLSERVICE
  win_service:
    name: MSSQLSERVER
    state: restarted
    force_dependent_services: yes

- name: Start service MSSQLSERVICE, if not started
  win_service:
    name: SQLSERVERAGENT
    state: started
    force_dependent_services: yes

- name: SQL Server Configuration Options
  win_shell: sqlcmd.exe -i "C:\Packages\SAP\sqlScripts\SQLPostConfig\sap_post_config_03.sql" -v database="{{ environment_sid }}"


- name: delete any mapped drives under Z
  win_mapped_drive:
    letter: X
    state: absent