USE $(database)
GO

/******Create index SRRELROLES 1 ******/
CREATE NONCLUSTERED INDEX [SRRELROLES~003] ON $(schema).[SRRELROLES]
(
	[CLIENT] ASC,
	[UTCTIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** 2 ******/
CREATE NONCLUSTERED INDEX [SRRELROLES~002] ON $(schema).[SRRELROLES]
(
	[CLIENT] ASC,
	[ROLETYPE] ASC,
	[OBJTYPE] ASC,
	[OBJKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** 3 ******/
CREATE NONCLUSTERED INDEX [SRRELROLES~001] ON $(schema).[SRRELROLES]
(
	[ROLEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
