USE $(database)
GO

/*** Takes 27 minutes ***/

/****** Create index GEOOBJR 1 ******/
CREATE NONCLUSTERED INDEX [GEOOBJR~002] ON $(schema).[GEOOBJR]
(
	[CLIENT] ASC,
	[GUIDLOC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Create index GEOOBJR 2 ******/
CREATE NONCLUSTERED INDEX [GEOOBJR~003] ON $(schema).[GEOOBJR]
(
	[CLIENT] ASC,
	[OBJTYPE] ASC,
	[OBJSUBTYPE] ASC,
	[OBJKEY] ASC,
	[LOGSYS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Create index GEOOBJR 3 ******/
CREATE NONCLUSTERED INDEX [GEOOBJR~004] ON $(schema).[GEOOBJR]
(
	[CLIENT] ASC,
	[OBJKEY] ASC,
	[OBJTYPE] ASC,
	[LOGSYS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
