---
# Copy ASCS paramaters file
- name: Copy ASCS parameters files
  template:
    src: templates/ascs.j2
    dest: C:\Install\AutomationParameters\ascs.params
    newline_sequence: '\r\n'

# Run SAP installer for ASCS server
- name: Run SAP installer for ASCS
  win_shell: C:\SWPM\sapinst.exe SAPINST_INPUT_PARAMETERS_URL=C:\Install\AutomationParameters\ascs.params SAPINST_EXECUTE_PRODUCT_ID=NW_ABAP_ASCS:NW740SR2.MSS.CP SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  become: yes
  become_method: runas
  become_user: "{{ sap_install_user }}"
  vars:
    ansible_become_password: "{{ sap_install_password }}"
    
# Set physical memory limit on ASCS server
- name: Set physical memory parameter on ASCS server
  win_lineinfile:
    path: "C:\\usr\\sap\\{{ environment_sid }}\\SYS\\profile\\DEFAULT.PFL"
    line: "PHYS_MEMSIZE = 30%"
  register: phys_memsize

# Restart ASCS server
- name: Restart SAP system on ASCS server
  win_shell: | 
    & "C:\\Program Files\\SAP\\hostctrl\\exe\\sapcontrol.exe" -nr 0 -host "{{ ascs_host }}" -user "{{ sap_install_user }}" "{{ sap_install_password }}" -function RestartSystem
    Start-Sleep 120
  args:
    executable: powershell
  when: phys_memsize.changed == true