---
# Ensure Working Directories are ceated    
- name: Ensure working directory is created
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - C:\Packages
    - C:\Packages\Commvault\Restore

# Update CV Restore XML File
- name: pdate CV Restore XML File
  template:
    src: templates/cv_crm_restore.xml.j2
    dest: "C:\\Packages\\Commvault\\Restore\\cv_crm_restore.xml"
    newline_sequence: '\r\n'
    backup: yes

# Install CV SQL Agent
- name: cv_sql_agent_install
  script: scripts/cv_sqlagent_install.ps1 >
    -storName "{{ storage_account_name }}"
    -storKey "{{ storage_account_key }}"

# Ensure directory structure for SAP database is present
- name: Create directory structure for SAP database
  win_file:
    path: "I:\\{{ environment_sid }}\\{{ environment_sid }}{{ item }}"
    state: directory
  with_items:
    - LOG
    - DATA1
    - DATA2
    - DATA3
    - DATA4
    - DATA5
    - DATA6
    - DATA7
    - DATA8

# Trigger Data Restore
- name: Trigger Data Restore
  win_shell: | 
    C:\Packages\CommVault\Restore\cv_crm_restore.bat /silent
  become: yes
  become_method: runas
  become_user: "{{ ansible_user }}"
  vars:
    ansible_become_password: "{{ ansible_password }}"
  ignore_errors: true