---
- hosts: ISU_Database
  gather_facts: true
  any_errors_fatal: true

  vars_files:
    - "vars/windows.yaml"
  
  tasks: 

  - include_role:
      name: sap_sql_post_config
      tasks_from: sap_sql_post_config_01