---
- hosts: data-isu
  gather_facts: true
  any_errors_fatal: true
  vars:
        sap_sid: "{{ isu_sid }}"
  vars_files:
    - vars/windows.yaml
    - vars/local_vars.yaml
  
  tasks: 

  - include_role:
      name: sap_sql_post_config
      tasks_from: sap_sql_post_config_01